Modernise plugin for Lean 4: add bin/download, drop Lean 3, support all four platforms, use tar.zst, update CI

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -26,45 +26,16 @@ install_lean() {
   local install_type=$1
   local version=$2
   local install_path=$3
+  local download_path=$4
 
   if [ "$install_type" != "version" ]; then
     fail "asdf-lean supports release installs only"
   fi
 
-  local platform
-  local extension
+  [ -d "$download_path" ] || fail "Download path not found: $download_path"
 
-  case "$OSTYPE" in
-    darwin*) platform="darwin" extension="zip" ;;
-    linux*) platform="linux" extension="tar.gz" ;;
-    *) fail "Unsupported platform" ;;
-  esac
-
-  local fullname="lean-${version}-${platform}"
-  local download_url="https://github.com/leanprover/lean/releases/download/v${version}/${fullname}.${extension}"
-  local source_path="${install_path}/${fullname}.${extension}"
-  local extracted_path="${install_path}/${fullname}"
-
-  (
-    echo "∗ Downloading and installing lean..."
-    curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-    case "$platform" in
-      darwin)
-        unzip -q "$source_path" -d "$install_path" || fail "Could not uncompress"
-        cd "$extracted_path"
-        mv ./* ../ && cd ..
-        rm -rf "$source_path" "$extracted_path"
-        ;;
-      linux)
-        tar zxf "$source_path" -C "$install_path" --strip-components=1 || fail "Could not uncompress"
-        rm -rf "$source_path"
-        ;;
-    esac
-    echo "The installation was successful!"
-  ) || (
-    rm -rf "$install_path"
-    fail "An error occurred"
-  )
+  cp -r "$download_path"/. "$install_path/"
+  echo "The installation was successful!"
 }
 
-install_lean "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_lean "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH"
